### ISSUE TITLE
Lang de_DE

### ISSUE THREAD

**Issue by Alexey-T** [dinkumoil/cuda_file_type_profile#10]
@dinkumoil 
Can I ask you to update de_DE translation, please? It is outdated.
It is here:
https://sourceforge.net/projects/cudatext/files/addons/translations/

**Comment by dinkumoil** [comment]
Yes, this is something I could do.

Some questions:

1. How can I figure out the context of a translation item, i.e. the place in CudaText where it is used? Appropriate translation without context is impossible sometimes.
2. You said the translation is outdated. Is `<CudaText-dir>\data\lang\translation template.ini` up to date?
3. How can I submit changes to the translation file? Ideally I would like to avoid to check out the whole CudaText repo. Moreover I'm used to use SVN instead of Git, thus I'm not comfortable with Git and consider it to be rather complicated.

**Comment by Alexey-T** [comment]
1. Looking at item in "translation template.ini" vs UI of Cudatext, finding this item

2. template- yes, of course.

3.  No git. just send me the ready zip to email support (@) uvviewsoft.com

**Comment by dinkumoil** [comment]
All right, I will try my best to send you an updated file in the next days.

**Comment by dinkumoil** [comment]
Translation files have been sent.

**Comment by Alexey-T** [comment]
Published, thank you.
