### ISSUE TITLE
smth broken with CP866 and .nt files

### ISSUE THREAD

**Issue by Alexey-T** [dinkumoil/cuda_file_type_profile#7]
- i made new.nt file with text `просто` , saved file as cp866.
other app shows file OK in cp866.

- my config
[BatchScript]
FileExts=.cmd;.bat;.nt
Encoding=cp866
EolFormat=

- i open file in Cud and text is broken
![Screenshot from 2019-06-07 00-09-23](https://user-images.githubusercontent.com/4154978/59066808-94018b80-88b8-11e9-94bb-4d6f34a0f302.png)

statusbar shows "cp866" thoug
Linux Ubuntu 18

**Comment by Alexey-T** [comment]
@kvichans Do you confirm it in Win?

**Comment by Alexey-T** [comment]
if I reload file in utf8, then reload it in cp866, it shows OK.

**Comment by dinkumoil** [comment]
I tested it on my (german) Windows machine - no problem. Hex content of my test file: `AF E0 AE E1 E2 AE`.

Sequence I've used to produce the test file:

1. Right-click in Windows Explorer window, select `New -> Text file`
2. Set file's name to `Test.nte`.
3. Open CudaText and open config file of my plugin.
4. Add the following lines:

```
[Test]
FileExts=.nte
Encoding=cp866
```

5. Open file from step 2, CudaText status line shows `cp866`.
6. After file is loaded, paste `просто` to it and save.
7. Close and reopen CudaText, load the test file.

**Please note:** You can not create a new file with CudaText, paste some text and save it with an extension you expect to trigger code page switching. Code page switching is only done when a file is loaded.

**Comment by Alexey-T** [comment]
But what if you repeat my steps? do you see text as broken?

**Comment by Alexey-T** [comment]
problem with Cud API PROC_ENC. i load any file in utf8, then enter in Console

>>> ed.set_prop(PROP_ENC, 'cp866')

this don't reload file in cp866.
so plugin must NOT use PROP_ENC. it must use commands from module "cudatext_cmd".

**Comment by Alexey-T** [comment]
cmd_Encoding_ansi_Reload      = 2750
cmd_Encoding_utf8bom_Reload   = 2751
cmd_Encoding_utf8nobom_Reload = 2752
cmd_Encoding_utf16le_Reload   = 2753
cmd_Encoding_utf16be_Reload   = 2754
cmd_Encoding_cp1250_Reload    = 2755
cmd_Encoding_cp1251_Reload    = 2756
cmd_Encoding_cp1252_Reload    = 2757
cmd_Encoding_cp1253_Reload    = 2758
cmd_Encoding_cp1254_Reload    = 2759
cmd_Encoding_cp1255_Reload    = 2760
cmd_Encoding_cp1256_Reload    = 2761
cmd_Encoding_cp1257_Reload    = 2762
cmd_Encoding_cp1258_Reload    = 2763
cmd_Encoding_mac_Reload       = 2764
cmd_Encoding_iso1_Reload      = 2765
cmd_Encoding_iso2_Reload      = 2766
cmd_Encoding_cp437_Reload     = 2770
cmd_Encoding_cp850_Reload     = 2771
cmd_Encoding_cp852_Reload     = 2772
cmd_Encoding_cp866_Reload     = 2773
cmd_Encoding_cp874_Reload     = 2774
cmd_Encoding_cp932_Reload     = 2775
cmd_Encoding_cp936_Reload     = 2776
cmd_Encoding_cp949_Reload     = 2777
cmd_Encoding_cp950_Reload     = 2778

**Comment by kvichans** [comment]
> so plugin must NOT use PROP_ENC

Need more explanations.

**Comment by Alexey-T** [comment]
Prop_enc does change of enc without reloading file. Plugin needs reloading.

**Comment by dinkumoil** [comment]
I can confirm the issue.

Test sequence (Windows 7 x64, CudaText 1.81.2.0 x64):

1. Open CudaText and load plugin config file.
2. Change `Encoding` to `cp866` and add `EolFormat=` (no value).
3. Create a new file **in** CudaText (`(menu) File -> New File`).
4. Set encoding of the file to `cp866` using context menu of status bar's encoding indicator.
5. Paste `просто` into it and save it as `Test.nt`.
6. Close the file's tab.
7. Go to `(menu) File -> Open recent -> Clear list`
8. Close CudaText.
9. Reopen CudaText and load the file saved in step 5.

Though the status bar shows `cp866` as the encoding the file's content is garbled. The important step to get that result is step 7 of the list above. As long as a file is in the recent files list CudaText remembers its state when it is opened the next time. It's like an implicit sesssion feature.

This feature was the reason for me to include debug messages into the code because it drove me crazy during development that encoding switching seemed to work sometimes and sometimes not. Then I became aware of this implict session feature (normal sessions are turned off in my `user.json`) and how to overcome it (clear recent file list). BTW: It would be useful if there would be a setting to deactivate this behaviour.

My first approach was to use `cmd_Encoding_xxx_Reload`. But then I found the `PROP_ENC` method in the wiki and decided to take this method because it is more user friendly to use encoding names like `cp850` than plain numbers.

I'm not at my machine until the evening of Monday, 2019-06-11 and will have no time to fix the issue.

**Comment by Alexey-T** [comment]
The code can look like:
```
import cudatext_cmd
ENC_MAP = {
  'cp866': cudatext_cmd.cmd_Encoding_cp866_Reload,
...
}
```
instead of `ed.set_prop(s,'')` do
```
n = ENC_MAP.get(s, cudatext_cmd.????)
ed.cmd(n)
```

**Comment by dinkumoil** [comment]
Yes, good suggestion. This requires maintenance of the mapping list to amend eventually newly added encodings, but alright, this is likely to be rare.

What is your opinion about introducing a setting to turn off that implicit session feature?

**Comment by Alexey-T** [comment]
Cud has option ui_max_history_files
History: Max items in "settings/history files.json" (0..400)
must be enough?

**Comment by dinkumoil** [comment]
> must be enough?

IMHO no. I don't want to loose the recent files feature, I want to be able to turn off the implicit session feature **only**.

**Comment by Alexey-T** [comment]
Cud cannot reopen recent file without restoring its encoding or caret pos. Not sure it's good to have.

**Comment by dinkumoil** [comment]
I've found some time to implement the fix but could spend only limited time for testing. Please have a look at the new version.

Have a nice weekend, will be back at Tuesday.

**Comment by Alexey-T** [comment]
It's solved. thanks. Have a nice weekend too.

Publishing the plugin...

**Comment by dinkumoil** [comment]
Thank you!
