### ISSUE TITLE
React to wrong value of encoding and EOL

### ISSUE THREAD

**Issue by Alexey-T** [dinkumoil/cuda_file_type_profile#8]
instead of v = d[index] you should use
```
v = d.get(index)
if v is None: return
```
@dinkumoil

**Comment by dinkumoil** [comment]
Do you think that would be sufficient (replacement for lines 157 and 158)?

```Python
if settings_applied:
    return True
else:
    return False
```

This code is only executed if the file's extension is part of the extension list, thus one of the settings **should** have been applied. If `settings_applied` is `False` something went wrong, none of the possible settings has been applied. Hence it is not necessary to continue searching the INI file's data model.

Did I got your thoughts?

**Comment by Alexey-T** [comment]
it is not sufficient. you need to fix it if user writes encoding name with typo- 'cx866', 'anki'. and EOL with typo: "cklz".

**Comment by dinkumoil** [comment]
What do you think happens when users do this?

**Comment by Alexey-T** [comment]
i think plugin crashes, because it cannot get command id from dict.

**Comment by dinkumoil** [comment]
I think it will not crash, instead it will ignore the wrong value.

```Python
if key_encoding in section_items and section_items[key_encoding].lower() in enc_map:
```

At first I check whether the `Encoding`/`EolFormat` key is part of the INI file section, whose file extension list contains the extension of the current file. Since Python does **not** complete boolean evaluation, the second check and the content of the `If`-block will not be executed if this is not the case. Hence it is valid to check in the same line, whether the value of the `Encoding`/`EolFormat` key is part of the mapping dict. If not, the `If`-block will not be executed.

I can not see a piece of code which will cause a crash in case of a wrong encoding/EOL format. Do I miss something?

**Comment by Alexey-T** [comment]
You are right, sorry.

**Comment by dinkumoil** [comment]
No problem, I like it that you keep an eye even on the plugins you publish through your software. Much appreciated.
