### ISSUE TITLE
Talks

### ISSUE THREAD

**Issue by Alexey-T** [dinkumoil/cuda_file_type_profile#9]
@dinkumoil I appreciate your work on plugin. Don't you want to make LSP plugin? LSP is Microsoft's protocol to support autocompletions for all syntaxes - using web server which handles syntax. 
https://langserver.org/

I would donate some $ for this work.

**Comment by dinkumoil** [comment]
Thank you for your question. Unfortunately I have to decline it.

As I already told you I'm an absolute beginner in Python, thus at first I would have to learn the language and, moreover, its libraries and frameworks. I have also no knowledge about LSP. Since I'm busy in my job I have only limited spare time for other things and would be overwhelmed to handle such a project.

BTW: My highest respect for your engaged and thoroughly work on CudaText, quick responses to new issues and quick deployment of solutions. It's exemplary.
